[[questions]]
type = "MultipleChoice"
prompt.prompt = "Quel est le rôle d'un nœud dans ROS 2 ?"
prompt.distractors = [
  "Une unité de stockage pour les données.",
  "Un outil pour visualiser les états du robot.",
  "Un fichier de configuration pour définir les paramètres."
]
answer.answer = "Un processus qui effectue des calculs et des communications."
context = "Les nœuds sont les blocs de construction fondamentaux d'un système ROS 2, responsables de réaliser des calculs et de communiquer avec d'autres nœuds."
id = "339fb93a-3ae8-4f28-8fac-8b96a7f8031"
